modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/HO-Artisan/Mufog/issues"

[[mods]]
modId="mufog"
version="${version}"
displayName="Mufog"
logoFile="icon.png"
authors="HO-Artisan,Chemiofitor"
description='''
The Smithing System based on Datapack!
'''

[[dependencies.mufog]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mufog]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.mufog]]
modId="architectury"
mandatory=true
versionRange="[9.1,)"
ordering="NONE"
side="BOTH"
